// This is just some sample data so you don't have to think of your own!
module.exports = [
  {
    "id":49,
    "title":"In a World of Middleware, Who Needs Monolithic Applications?",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/000/049/13-mar-2009-11-05-in-a-world-of-middleware-who-needs-monolithic-applications-jon-crosby-preview-original.png?1422308345",
    "slug":"mwrc2009-in-a-world-of-middleware-who-needs-monolithic-applications",
    "recorded_at":"2009-03-13T18:05:00.000Z",
    "event":"MountainWest RubyConf 2009",
    "rating":"Not yet Rated",
    "abstract":null,
    "post_date":"2010-09-04T07:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"H-mctufxiQ4",
    "views":1441,
    "views_last_7":2,
    "views_last_30":11,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Jon",
        "last_name":"Crosby",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":856,
    "title":"Getting Down To Earth: Geospatial Analysis With Rails",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/000/856/856-railsconf2012-getting-down-to-earth-geospatial-analysis-with-rails-thumb_0003-original.png?1422312283",
    "slug":"railsconf2012-getting-down-to-earth-geospatial-analysis-with-rails",
    "recorded_at":"2012-04-23T18:30:00.000Z",
    "event":"RailsConf 2012",
    "rating":"Everyone",
    "abstract":"It is no secret that location has become ubiquitous. Mobile GPS, available data sets, and easy-to-use mapping services have brought geospatial information within reach of web developers. Location already plays a significant role in many of the major services such as Twitter, Facebook, and Google, not to mention legions of startups.\r\n\r\nHowever, for those of us implementing more than the most trivial features, it is also true that location is challenging. A significant learning curve awaits us, involving spatial databases, coordinate systems, interchange formats, and plenty of math. Our Ruby-based tools lag a bit behind those available to our Java- and Python-oriented colleagues, and effective documentation is scarce.\r\n\r\nThis presentation aims to jump-start Rails developers hoping to go beyond putting a few pushpins on a Google Map. Rather than spending a lot of time explaining the many concepts involved, we'll bypass the learning curve and jump straight into walking through code for a few nontrivial applications. The hope is that the conceptual knowledge will come naturally as a result of seeing it in action, but pointers to online resources will also be provided to fill in any gaps.\r\n\r\nA thorough understanding of Ruby, Rails, ActiveRecord, and SQL will be assumed. No prior knowledge of GIS or computational geometry will be required, though it may be helpful.",
    "post_date":"2012-05-03T07:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"QI0e2jkUbkk",
    "views":2616,
    "views_last_7":9,
    "views_last_30":27,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Daniel",
        "last_name":"Azuma",
        "aka_name":"",
        "twitter_handle":"danielazuma"
      }
    ]
  },
  {
    "id":2448,
    "title":"Of Buyers And Renters and keeping a roof over our heads",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/002/448/sebastian_delmont-original.png?1422324888",
    "slug":"railsconf2013-of-buyers-and-renters-and-keeping-a-roof-over-our-heads",
    "recorded_at":"2013-04-30T17:30:00.000Z",
    "event":"RailsConf 2013",
    "rating":"Everyone",
    "abstract":"What do home ownership and leveraged buyouts can teach us about how to use technical debt to our advantage? How can we sleep soundly at night when we have accumulated mountains and mountains of technical debt? When is good enough good enough and when are we just deceiving ourselves?",
    "post_date":null,
    "announce_date":null,
    "host":"youtube",
    "embed_code":"XakfJ2spb3w",
    "views":1697,
    "views_last_7":5,
    "views_last_30":12,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Sebastian",
        "last_name":"Delmont",
        "aka_name":null,
        "twitter_handle":"sd"
      }
    ]
  },
  {
    "id":7192,
    "title":"Intro",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/192/Capture-original.PNG?1449180649",
    "slug":"cssconfeu2014-intro",
    "recorded_at":null,
    "event":"CSSConf EU 2014",
    "rating":"Everyone",
    "abstract":"When not working on UNIQLO's upcoming mobile web site, Jed enjoys singing barbershop harmonies, competing in pun contests, and introducing conferences entirely in CSS.",
    "post_date":"2015-12-03T15:10:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"bdQ-Okw9gPY",
    "views":4,
    "views_last_7":0,
    "views_last_30":5,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Jed",
        "last_name":"Schmidt",
        "aka_name":null,
        "twitter_handle":"jedschmidt"
      }
    ]
  },
  {
    "id":7194,
    "title":"Validate Me",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/194/Capture-original.PNG?1449180796",
    "slug":"cssconfeu2014-validate-me",
    "recorded_at":null,
    "event":"CSSConf EU 2014",
    "rating":"Everyone",
    "abstract":"As creatives we struggle with fair amount of self-doubt. How do we free ourselves from relying on external validation of our efforts? How do we fight impostor syndrome and confirmation bias? How do we prevent ourselves from falling into the burnout and depression pit, or more importantly how do we recover?\r\n\r\nLessons learned on cutting yourself some slack and surrounding yourself with people who will empower you to do so.",
    "post_date":"2015-12-03T15:12:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"ZlxpF9taprI",
    "views":1,
    "views_last_7":0,
    "views_last_30":5,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Karolina",
        "last_name":"Szczur",
        "aka_name":null,
        "twitter_handle":"karolinaszczur"
      }
    ]
  },
  {
    "id":7134,
    "title":"River trail. Parallel computing in JavaScript.",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/134/Capture-original.PNG?1449170561",
    "slug":"jsconfus2012-river-trail-parallel-computing-in-javascript",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T12:22:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"IcYsiVEIPhA",
    "views":3,
    "views_last_7":0,
    "views_last_30":4,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Stephan",
        "last_name":"Herhut",
        "aka_name":"",
        "twitter_handle":"herhut"
      }
    ]
  },
  {
    "id":7169,
    "title":"Booting Docker Images over Bittorrent",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/169/Capture-original.PNG?1449177436",
    "slug":"nodeconf2014-booting-docker-images-over-bittorrent",
    "recorded_at":null,
    "event":"NodeConf 2014",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T14:16:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"PdBHYYHY7z8",
    "views":2,
    "views_last_7":0,
    "views_last_30":5,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Mathias",
        "last_name":"Buus",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":396,
    "title":"Cleanliness Is Next to Domain Specificity",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/000/396/vlcsnap-2010-10-05-15h22m15s246-original.png?1422309561",
    "slug":"rubyconf2007-cleanliness-is-next-to-domain-specificity",
    "recorded_at":"2007-11-04T23:00:00.000Z",
    "event":"Ruby Conference 2007",
    "rating":"Everyone",
    "abstract":null,
    "post_date":"2010-10-05T22:23:19.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"QAThcdbrbVg",
    "views":879,
    "views_last_7":0,
    "views_last_30":3,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Ben",
        "last_name":"Scofield",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":7218,
    "title":"Cgroups, namespaces, and beyond: what are containers made from?",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/218/Capture-original.PNG?1449589732",
    "slug":"dockerconeu2015-cgroups-namespaces-and-beyond-what-are-containers-made-from",
    "recorded_at":null,
    "event":"DockerCon EU 2015",
    "rating":"Everyone",
    "abstract":"Linux containers are different from Solaris Zones or BSD Jails: they use discrete kernel features like cgroups, namespaces, SELinux, and more. We will describe those mechanisms in depth, as well as demo how to put them together to produce a container. We will also highlight how different container runtimes compare to each other. ",
    "post_date":"2015-12-08T08:47:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"sK5i-N34im8",
    "views":11,
    "views_last_7":3,
    "views_last_30":22,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Jérôme",
        "last_name":"Petazzoni",
        "aka_name":"",
        "twitter_handle":"jpetazzo"
      }
    ]
  },
  {
    "id":7139,
    "title":"JSConf 2012 Welcome Video",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/139/Capture-original.PNG?1449171107",
    "slug":"jsconfus2012-jsconf-2012-welcome-video",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T12:31:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"vs6rCGwjzq8",
    "views":3,
    "views_last_7":0,
    "views_last_30":4,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[

    ]
  },
  {
    "id":7127,
    "title":"Build anything",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/127/Capture-original.PNG?1449165592",
    "slug":"jsconfus2012-build-anything",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T10:59:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"SPyIcrKbmhI",
    "views":4,
    "views_last_7":0,
    "views_last_30":6,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Remy",
        "last_name":"Sharp",
        "aka_name":null,
        "twitter_handle":null
      }
    ]
  },
  {
    "id":7130,
    "title":"one day of life in V8",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/130/Capture-original.PNG?1449170145",
    "slug":"jsconfus2012-one-day-of-life-in-v8",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T12:15:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"Z_q6iw3h48s",
    "views":2,
    "views_last_7":0,
    "views_last_30":4,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Vyacheslav",
        "last_name":"Egorov",
        "aka_name":null,
        "twitter_handle":null
      }
    ]
  },
  {
    "id":7137,
    "title":"Brûlons les musées",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/137/Capture-original.PNG?1449170952",
    "slug":"jsconfus2012-brulons-les-musees",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T12:28:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"zwoiwoVNaCQ",
    "views":1,
    "views_last_7":1,
    "views_last_30":1,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Jacob",
        "last_name":"Thornton",
        "aka_name":"",
        "twitter_handle":"fat"
      }
    ]
  },
  {
    "id":7118,
    "title":"How to prepare a distributed nodejs application",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/118/Capture-original.PNG?1449161822",
    "slug":"jsconfus2013-how-to-prepare-a-distributed-nodejs-application",
    "recorded_at":null,
    "event":"JSConf US2013",
    "rating":"Everyone",
    "abstract":"Ingredients:\r\n\r\n1x nodejs application, the bigger the better\r\nA handful of external services, AWS will do\r\nSome Cachaça or good Pálinka\r\nPreparation:\r\nWith a sharp eye slice open your server and remove its guts, put that aside ...\r\n\r\nKeyword soup: microframework for distributed nodejs applications with service discovery and remote dependency control.",
    "post_date":"2015-12-03T09:56:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"7HxIWpuH1Wc",
    "views":1,
    "views_last_7":0,
    "views_last_30":4,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Daniel",
        "last_name":"Tralamazza",
        "aka_name":null,
        "twitter_handle":"tralamazza"
      }
    ]
  },
  {
    "id":7136,
    "title":"Politics (or how we all make a difference)",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/136/Capture-original.PNG?1449170865",
    "slug":"jsconfus2012-politics-or-how-we-all-make-a-difference",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T12:27:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"MXgyEDoqtps",
    "views":1,
    "views_last_7":1,
    "views_last_30":3,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Rick",
        "last_name":"Falkvinge",
        "aka_name":"",
        "twitter_handle":"Falkvinge"
      }
    ]
  },
  {
    "id":4626,
    "title":"Hadoop in 5 Minutes or Less",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/004/626/work-original.jpg?1422374884",
    "slug":"strataconf2014-hadoop-in-5-minutes-or-less",
    "recorded_at":"2014-02-12T16:25:00.000Z",
    "event":"Strata 2014",
    "rating":"Everyone",
    "abstract":"This five-minute keynote will provide a quick overview of some of the more surprising things Hadoop is capable of in 5 minutes or less.\r\n\r\nThis keynote is sponsored by MapR Technologies",
    "post_date":"2014-09-24T06:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"wMCKtrjrU_E",
    "views":170,
    "views_last_7":0,
    "views_last_30":3,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"John",
        "last_name":"Schroeder",
        "aka_name":null,
        "twitter_handle":null
      }
    ]
  },
  {
    "id":557,
    "title":"Data Stories",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/000/557/ML1_05_JeremyHinegardner-original.jpg?1422311074",
    "slug":"scotlandruby2011-data-stories",
    "recorded_at":"2011-04-08T13:15:00.000Z",
    "event":"Scotland Ruby 2011",
    "rating":"Everyone",
    "abstract":"We are inundated with copious amounts of data day in and day out. We manage volumes of the stuff. We Produce it, archive it, throw it away, and sometimes, if we are lucky, we look at it and we find a story.\r\n\r\nThis talk is about examining and visualizing data to teasing out its story, or lack of one.",
    "post_date":null,
    "announce_date":null,
    "host":"youtube",
    "embed_code":"qcH2QA2PkYI",
    "views":875,
    "views_last_7":1,
    "views_last_30":3,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Jeremy",
        "last_name":"Hinegardner",
        "aka_name":"",
        "twitter_handle":"copiousfreetime"
      }
    ]
  },
  {
    "id":3281,
    "title":"Five machine learning techniques that you can use in your Ruby apps today",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/003/281/benjamin-original.png?1422384150",
    "slug":"mwrc2014-five-machine-learning-techniques-that-you-can-use-in-your-ruby-apps-today",
    "recorded_at":"2014-03-21T16:30:00.000Z",
    "event":"MountainWest RubyConf 2014",
    "rating":"Everyone",
    "abstract":"Machine learning is everywhere these days. Features like search, voice recognition, recommendations - they’ve become so common that people have started to expect them. They’re starting to expect the apps we build to be smarter.\r\nTen years ago, machine learning and data mining techniques were only available to the people dedicated enough to dig through the math. Now that’s not the case.\r\nThe most common machine learning techniques are well known. Standard approaches have been developed. And, fortunately for us, many of these are available as ruby gems. Some are even easy to implement yourself.\r\nIn this presentation we’ll cover five important machine learning techniques that can be used in a wide range of applications. It will be a wide and shallow introduction, for Rubyists, not mathematicians - we’ll have plenty of simple code examples.\r\nBy the end of the presentation, you won’t be an expert, but you’ll know about a class of tools you may not have realized were available.",
    "post_date":null,
    "announce_date":null,
    "host":"youtube",
    "embed_code":"crziu7dk6Vw",
    "views":1484,
    "views_last_7":1,
    "views_last_30":6,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Benjamin",
        "last_name":"Curtis",
        "aka_name":null,
        "twitter_handle":"stympy"
      }
    ]
  },
  {
    "id":7185,
    "title":"Intro.css",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/185/Capture-original.PNG?1449179857",
    "slug":"cssconfeu2013-intro-css",
    "recorded_at":null,
    "event":"CSSConf EU 2013",
    "rating":"Everyone",
    "abstract":"Jed is the guy behind projects as diverse as browserver, ramendan, and 140byt.es, and notorious for his entertainer qualities. As CSSconf.eu’s host he will guide you through the program.",
    "post_date":"2015-12-03T14:57:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"rXmVDXZAce8",
    "views":1,
    "views_last_7":0,
    "views_last_30":1,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Jed",
        "last_name":"Schmidt",
        "aka_name":null,
        "twitter_handle":"jedschmidt"
      }
    ]
  },
  {
    "id":7129,
    "title":"mojito your stuff runs on both sides",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/129/Capture-original.PNG?1449165791",
    "slug":"jsconfus2012-mojito-your-stuff-runs-on-both-sides",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T11:02:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"OY1VS61q3LM",
    "views":1,
    "views_last_7":1,
    "views_last_30":2,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Bruno",
        "last_name":"Fernandez-Ruiz",
        "aka_name":"",
        "twitter_handle":"olympum"
      }
    ]
  },
  {
    "id":3795,
    "title":"Massive.js",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/003/795/work-original.jpg?1422370187",
    "slug":"riojsconf2013-massive-js",
    "recorded_at":"2013-03-09T07:00:00.000Z",
    "event":"Rio.JS Conf 2013",
    "rating":"Everyone",
    "abstract":null,
    "post_date":"2014-06-17T06:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"1B9p691U_Ms",
    "views":188,
    "views_last_7":1,
    "views_last_30":2,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Erich",
        "last_name":"Gamma",
        "aka_name":null,
        "twitter_handle":"ErichGamma"
      }
    ]
  },
  {
    "id":7133,
    "title":"Stranger in these parts. A hired gun in the js corral",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/133/Capture-original.PNG?1449170463",
    "slug":"jsconfus2012-stranger-in-these-parts-a-hired-gun-in-the-js-corral",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T12:20:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"hHytsQkVlhA",
    "views":3,
    "views_last_7":0,
    "views_last_30":4,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Andy",
        "last_name":"Wingo",
        "aka_name":null,
        "twitter_handle":null
      }
    ]
  },
  {
    "id":7128,
    "title":"repl.it",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/128/Capture-original.PNG?1449165692",
    "slug":"jsconfus2012-repl-it",
    "recorded_at":null,
    "event":"JSConf uS2012",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T11:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"XfxH-JDF7Xk",
    "views":0,
    "views_last_7":0,
    "views_last_30":0,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Max",
        "last_name":"Shawabkeh",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":7165,
    "title":"Javascript Flow Control",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/165/Capture-original.PNG?1449177081",
    "slug":"nodeconf2014-javascript-flow-control",
    "recorded_at":null,
    "event":"NodeConf 2014",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T14:10:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"aqyv_FMp0n8",
    "views":0,
    "views_last_7":0,
    "views_last_30":0,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Stephen",
        "last_name":"Rivas JR",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":7221,
    "title":"How to be successful running Docker in Production",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/221/Capture-original.PNG?1449590686",
    "slug":"dockerconeu2015-how-to-be-successful-running-docker-in-production",
    "recorded_at":null,
    "event":"DockerCon EU 2015",
    "rating":"Everyone",
    "abstract":"John’s presentation will cover his lessons learned from running Docker in Production @ SalesforceIQ. Learn how to scale your registry using AWS and S3. Should you use Device Mapper or AUFS? Why run Swarm, Mesos, Kubernetes, or neither. Finally, know how persistent storage (Kafka, Cassandra, or SQL) can be run successfully with Docker in Production\r\nHis team focuses on Docker based solutions to power their SaaS infrastructure and developer operations.",
    "post_date":"2015-12-08T09:04:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"j6Ge4wP1yH0",
    "views":7,
    "views_last_7":6,
    "views_last_30":28,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"John",
        "last_name":"Fiedler",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":5775,
    "title":"Ending Keynote ",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/005/775/vlcsnap-2015-08-03-07h17m15s184-original.png?1438613609",
    "slug":"jschannelconf2015-ending-keynote",
    "recorded_at":"2015-07-18T17:30:00.000Z",
    "event":"JSChannel 2015",
    "rating":"Everyone",
    "abstract":"TBD",
    "post_date":"2015-08-03T07:53:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"m1qT9ODLcKY",
    "views":104,
    "views_last_7":2,
    "views_last_30":3,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Satty",
        "last_name":"Bhens",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":7220,
    "title":"Live migrating a container: pros, cons and gotchas",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/220/Capture-original.PNG?1449590602",
    "slug":"dockerconeu2015-live-migrating-a-container-pros-cons-and-gotchas",
    "recorded_at":null,
    "event":"DockerCon EU 2015",
    "rating":"Everyone",
    "abstract":" In this talk I will briefly show why you might want to live migrate a container, why you might want to avoid doing this and what can be done instead. The main topic of the talk would to demonstrate why live migrating a container is more complex than live migrating a virtual machines and what can be done with this complexity. ",
    "post_date":"2015-12-08T09:02:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"dUixUP2lKeE",
    "views":4,
    "views_last_7":3,
    "views_last_30":11,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Pavel",
        "last_name":"Emelyanov",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":6965,
    "title":"Consequences of an Insightful Algorithm",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/006/965/d1-sync.08_38_06_18.Still007-original.png?1449081746",
    "slug":"arrrrcamp2015-consequences-of-an-insightful-algorithm",
    "recorded_at":"2015-10-01T17:20:00.000Z",
    "event":"ArrrrCamp 2015",
    "rating":"Everyone",
    "abstract":"We have ethical responsibilities when coding. We're able to extract remarkably precise intuitions about an individual. But do we have a right to know what they didn't consent to share, even when they willingly shared the data that leads us there? A major retailer's data-driven marketing accidentially revealed to a teen's family that she was pregnant. Eek.\r\n\r\nWhat are our obligations to people who did not expect themselves to be so intimately known without sharing directly? How do we mitigate against unintended outcomes? For instance, a social network algorithm accidentally triggering painful memories for families grieving their child's death.\r\n\r\nWe design software for humans. Balancing human needs and business specs can be tough. It's crucial that we learn how to build in systematic empathy.\r\n\r\nIn this talk, we'll delve into specific examples of uncritical programming, and painful results from using insightful data in ways that were benignly intended. You'll learn ways we can integrate practices for examining how our code might harm individuals. We'll look at how to flip the paradigm, netting consequences that can be better for everyone.",
    "post_date":"2015-12-03T09:31:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"roSxrWNgwgc",
    "views":71,
    "views_last_7":3,
    "views_last_30":14,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Carina C.",
        "last_name":"Zona",
        "aka_name":"",
        "twitter_handle":"cczona"
      }
    ]
  },
  {
    "id":706,
    "title":"How GitHub Uses GitHub to Build GitHub",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/000/706/706-rubyconf2011-how-github-uses-github-to-build-github-thumb_0004-original.png?1422311654",
    "slug":"rubyconf2011-how-github-uses-github-to-build-github",
    "recorded_at":"2011-10-01T18:15:00.000Z",
    "event":"Ruby Conference 2011",
    "rating":"Everyone",
    "abstract":"Build features fast. Ship them. That's what we try to do at GitHub. Our process is the anti-process: what's the minimum overhead we can put up with to keep our code quality high, all while building features *as quickly as possible*? It's not just features, either: faster development means happier developers. This talk will dive into how GitHub uses GitHub: we'll look at some of our actual Pull Requests, the internal apps we build on our own API, how we plan new features, our Git branching strategies, and lots of tricks we use to get everyone â€” developers, designers, and everyone else â€” involved with new code. We think it's a great way to work, and we think it'll work in your company, too.",
    "post_date":"2011-12-01T08:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"MQZoy3VU3io",
    "views":5098,
    "views_last_7":13,
    "views_last_30":37,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Zach",
        "last_name":"Holman",
        "aka_name":"",
        "twitter_handle":"holman"
      }
    ]
  },
  {
    "id":6109,
    "title":"Internet of Things Militia: Paramilitary Training for your IoT devices",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/006/109/vlcsnap-2015-09-10-14h09m45s242-original.png?1441928338",
    "slug":"osbridge2015-internet-of-things-militia-paramilitary-training-for-your-iot-devices",
    "recorded_at":"2015-06-25T13:30:00.000Z",
    "event":"Open Source Bridge 2015",
    "rating":"Everyone",
    "abstract":"Security folk generally talk about how the Internet of Things is bad for security, but it also brings new sensors and connected devices that could co-operate in new and interesting ways. Could we use internet things to enhance security?\r\n",
    "post_date":"2015-09-10T16:40:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"SCTq3WnETOk",
    "views":336,
    "views_last_7":5,
    "views_last_30":17,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Terri",
        "last_name":"Oda",
        "aka_name":"",
        "twitter_handle":"terriko"
      }
    ]
  },
  {
    "id":7171,
    "title":"The Node Way",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/007/171/Capture-original.PNG?1449177573",
    "slug":"nodeconf2014-the-node-way",
    "recorded_at":null,
    "event":"NodeConf 2014",
    "rating":"Everyone",
    "abstract":"",
    "post_date":"2015-12-03T14:18:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"pTOuoCYM32w",
    "views":0,
    "views_last_7":0,
    "views_last_30":0,
    "license":"cc-by-sa-3.0",
    "attribution":"",
    "presenters":[
      {
        "first_name":"Fred K.",
        "last_name":"Schott",
        "aka_name":"",
        "twitter_handle":""
      }
    ]
  },
  {
    "id":2769,
    "title":"Lightning Talk: The Increasing Need for Software Developers",
    "image":"http://s3-us-west-2.amazonaws.com/confreaks-tv3/production/videos/images/000/002/769/YouTube-original.png?1422327423",
    "slug":"rmr2013-lightning-talk-the-increasing-need-for-software-developers",
    "recorded_at":"2013-09-26T19:16:00.000Z",
    "event":"Rocky Mountain Ruby 2013",
    "rating":"Everyone",
    "abstract":null,
    "post_date":"2013-10-27T07:00:00.000Z",
    "announce_date":null,
    "host":"youtube",
    "embed_code":"bthXzlCan6s",
    "views":626,
    "views_last_7":1,
    "views_last_30":2,
    "license":"cc-by-sa-3.0",
    "attribution":null,
    "presenters":[
      {
        "first_name":"Thomas",
        "last_name":"Frey",
        "aka_name":null,
        "twitter_handle":null
      }
    ]
  }
]
